### ISSUE TITLE
No content in harvest modal window / harvest fails

### ISSUE THREAD

**Issue by telezoic** [DigitalNZ/supplejack_manager#260]
Hi Folks,
I'm  working on a new production build of SJ (in DigitalOcean/Ubuntu21 and I'm running into an error where no preview content is visible  when I attempt a harvest (regardless of the parser I use), and the harvest fails (it hangs with a 
"Status: Initialising preview record... New preview record initialised. Waiting in queue..." message.
 I'm hoping you had some suggestions to solve this dilemma . . . 

I can't identify anything particularly useful in the logs, stepping the log level up, just gives me mongo success details. 

My output (via passenger)

```
App 86153 output: {"name":"supplejack_manager","hostname":"Solum","pid":86153,"level":30,"time":"2022-04-29T21:14:51.099+00:00","v":0,"msg":"[d0525091-9ac7-440c-adab-e1036c16f81e] [active_model_serializers] {:msg=>\"Rendered PreviewSerializer with ActiveModelSerializers::Adapter::Attributes (0.7ms)\"}"}
App 86153 output: {"name":"supplejack_manager","hostname":"Solum","pid":86153,"level":30,"time":"2022-04-29T21:14:51.100+00:00","v":0,"msg":"[d0525091-9ac7-440c-adab-e1036c16f81e] {:msg=>\"Request\", :request=>{:method=>\"PUT\", :path=>\"/previews/626c5549331ce35089c4f690.json\", :format=>:json, :controller=>\"PreviewsController\", :action=>\"update\", :status=>200, :duration=>16.57, :view=>1.27, :request_id=>\"d0525091-9ac7-440c-adab-e1036c16f81e\", :params=>\"{\\\"parser_code\\\"=>\\\"[FILTERED]\\\", \\\"parser_id\\\"=>\\\"626afeb3331ce370731964b9\\\", \\\"index\\\"=>nil, \\\"user_id\\\"=>\\\"624b3c68331ce345e2162606\\\", \\\"raw_data\\\"=>\\\"[FILTERED]\\\", \\\"harvested_attributes\\\"=>\\\"[FILTERED]\\\", \\\"api_record\\\"=>\\\"[FILTERED]\\\", \\\"status\\\"=>\\\"Posting preview record to API...\\\", \\\"deletable\\\"=>false, \\\"field_errors\\\"=>\\\"{}\\\", \\\"validation_errors\\\"=>nil, \\\"harvest_failure\\\"=>\\\"[FILTERED]\\\", \\\"harvest_job_errors\\\"=>nil, \\\"preview\\\"=>{\\\"parser_code\\\"=>\\\"[FILTERED]\\\", \\\"parser_id\\\"=>\\\"626afeb3331ce370731964b9\\\", \\\"index\\\"=>nil, \\\"user_id\\\"=>\\\"624b3c68331ce345e2162606\\\", \\\"raw_data\\\"=>\\\"[FILTERED]\\\", \\\"harvested_attributes\\\"=>\\\"[FILTERED]\\\", \\\"api_record\\\"=>\\\"[FILTERED]\\\", \\\"status\\\"=>\\\"Posting preview record to API...\\\", \\\"deletable\\\"=>false, \\\"field_errors\\\"=>\\\"{}\\\", \\\"validation_errors\\\"=>nil, \\\"harvest_failure\\\"=>\\\"[FILTERED]\\\", \\\"harvest_job_errors\\\"=>nil, \\\"format\\\"=>\\\"json\\\"}}\", :user_id=>nil, :time=>183177448.655804}}"}
```

I can see the process fail in the web console: 
![Screen Shot 2022-04-29 at 13 13 45](https://user-images.githubusercontent.com/444648/166067104-a5716508-5442-4096-ad2b-cebb1c83a399.png)

I can see the harvest fail in a mongo record preview: 
![Screen Shot 2022-04-29 at 14 17 27](https://user-images.githubusercontent.com/444648/166070444-1902f3f1-2e60-4921-82ee-a0f895d4c797.png)

the stacktrace from the preview above: 

```
HARVEST FAILURE BACKTRACE: 

{"_id":"626c3b5e331ce302e204efa6","backtrace":["/home/arquebusier/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:249:in `exception_with_response'","/home/arquebusier/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:129:in `return!'","/home/arquebusier/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rest-client-2.1.0/lib/restclient/request.rb:836:in `process_result'","/home/arquebusier/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rest-client-2.1.0/lib/restclient/request.rb:743:in `block in transmit'","/home/arquebusier/.rbenv/versions/3.0.3/lib/ruby/3.0.0/net/http.rb:960:in `start'","/home/arquebusier/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'","/home/arquebusier/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'","/home/arquebusier/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'","/home/arquebusier/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rest-client-2.1.0/lib/restclient.rb:70:in `post'","/data/sites/supplejack_worker/app/workers/api_update_worker.rb:31:in `perform'","/data/sites/supplejack_worker/app/workers/harvest_worker.rb:88:in `post_to_api'","/data/sites/supplejack_worker/app/workers/preview_worker.rb:93:in `enrich_record'","/data/sites/supplejack_worker/app/workers/preview_worker.rb:38:in `block in perform'","/data/sites/supplejack_worker/app/models/harvest_job.rb:76:in `block in records'","/home/arquebusier/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/bundler/gems/supplejack_common-4f52eec31007/lib/supplejack_common/oai/paginated_collection.rb:26:in `block in each'","/home/arquebusier/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/oai-1.1.0/lib/oai/client/resumable.rb:24:in `block in yield_from_response'","/home/arquebusier/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/oai-1.1.0/lib/oai/client/list_records.rb:18:in `block in each'","/home/arquebusier/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/oai-1.1.0/lib/oai/client/list_records.rb:17:in `each'","/home/arquebusier/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/oai-1.1.0/lib/oai/client/list_records.rb:17:in `each'","/home/arquebusier/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/oai-1.1.0/lib/oai/client/resumable.rb:23:in `yield_from_response'","/home/arquebusier/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/oai-1.1.0/lib/oai/client/resumable.rb:13:in `each'","/home/arquebusier/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/bundler/gems/supplejack_common-4f52eec31007/lib/supplejack_common/oai/paginated_collection.rb:19:in `each'","/data/sites/supplejack_worker/app/models/harvest_job.rb:75:in `each_with_index'","/data/sites/supplejack_worker/app/models/harvest_job.rb:75:in `records'","/data/sites/supplejack_worker/app/workers/preview_worker.rb:33:in `perform'","/home/arquebusier/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:196:in `execute_job'","/home/arquebusier/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:164:in `block (2 levels) in process'","/home/arquebusier/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sidekiq-6.4.1/lib/sidekiq/middleware/chain.rb:138:in `block in invoke'","/home/arquebusier/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/elastic-apm-4.5.0/lib/elastic_apm/spies/sidekiq.rb:35:in `call'","/home/arquebusier/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sidekiq-6.4.1/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'","/home/arquebusier/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sidekiq-6.4.1/lib/sidekiq/middleware/chain.rb:143:in `invoke'"],"created_at":"2022-04-30T07:24:14.648+12:00","exception_class":"RestClient::UnprocessableEntity","message":"422 Unprocessable Entity","updated_at":"2022-04-30T07:24:14.648+12:00","id":"626c3b5e331ce302e204efa6"}
```
 

My `manager.yml` 

```
# Example Supplejack Manager application.yml file
# Add account credentials and API keys here.
# See http://railsapps.github.com/rails-environment-variables.html
# This file should be listed in .gitignore to keep your settings secret!
# Each entry sets a local environment variable and overrides ENV variables in the Unix shell.
# For example, setting:
# GMAIL_USERNAME: Your_Gmail_Username
# makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]
# Add application configuration variables here, as shown below.
#
# This setup assumes that you have an API that runs on localhost:3000
# and a Worker running on localhost:3002.
# Running the Manager allows you to harvest in production environment.

development:
  WORKER_HOST: http://127.0.0.1:3002
  WORKER_KEY: WORKER_KEY
  API_HOST: http://127.0.0.1:3000
  HARVESTER_API_KEY: HARVESTER_KEY
  OTP_SECRET_KEY: YOUROTPSECRETKEY
  MFA_ENABLED: 'false'

test:
  WORKER_HOST: http://127.0.0.1:3002
  WORKER_KEY: WORKER_KEY
  API_HOST: http://127.0.0.1:3000
  HARVESTER_API_KEY: HARVESTER_KEY
  MFA_ENABLED: 'false'
  OTP_SECRET_KEY: c8e869e0ce9c139a53c0d0fcc43c5883ea784e874330c458c160b7f4a3d227c802439188f37695a1f023ef42ffc3568cbd28b8900d6a0daccdabc20f443e51d7

staging:
  WORKER_HOST: http://127.0.0.1:3002
  WORKER_KEY: WORKER_KEY
  API_HOST:  http://127.0.0.1:3000
  HARVESTER_API_KEY: HARVESTER_KEY
  OTP_SECRET_KEY: YOUROTPSECRETKEY
  MFA_ENABLED: 'false'


production:
  MANAGER_HOST: https://manager.primarch-digitalbc.ca
  WORKER_HOST: https://worker.primarch-digitalbc.ca
  WORKER_KEY: acfcf32e4754f88f82e4afcf3c90e4b8949ef3f5f08d60056806dd640f82c54014cf6065fa6469460de20d36a74ca266777a118399faff7b125b78da90281a45
  API_HOST: https://api.primarch-digitalbc.ca
  MONGO_HOSTS: mongodb+srv://corymbusprime.d0rvn.mongodb.net:27017
  HARVESTER_API_KEY: ay_K9sTMHhX57iYBsxrh
  OTP_SECRET_KEY: YOUROTPSECRETKEY
  MFA_ENABLED: 'false'
```

My api.yml

```


defaults: &defaults
  SOLR_PING: 'http://localhost:8982/solr/admin/ping'
  #HTTP_HOST: 'http://localhost:3000'
  HTTP_HOST: 'https://api.primarch-digitalbc.ca'
  WORKER_API_URL: 'https://worker.primarch-digitalbc.ca'
  WWW_DOMAIN: 'www.dev'
  DEVISE_MAILER: 'mailer@example.com'
  RESQUE_USER: 'admin'
  RESQUE_PASS: 'password'
  HARVESTER_IPS: '127.0.0.1'
  REQUEST_LIMIT_MAILER: 'develop@digitalnz.org'
  BLACKLIST_MAILER_TO: 'blacklist@mailer.com'
  BLACKLIST_MAILER_FROM: 'mailer@blacklist.org'
#  HTTP_HOST: 'http://test.host'
  MONGO_HOSTS: mongodb+srv://corymbusprime.d0rvn.mongodb.net:27017
  SECRET_TOKEN: 'ebf99718478a71d71222f6896d25b13890b17b9b'
  WORKER_KEY: acfcf32e4754f88f82e4afcf3c90e4b8949ef3f5f08d60056806dd640f82c54014cf6065fa6469460de20d36a74ca266777a118399faff7b125b78da90281a45




development:
  <<: *defaults

test:
  <<: *defaults
  SOLR_PING: 'http://test.host'
  HTTP_HOST: 'http://test.host'
  WWW_DOMAIN: 'test.host'

staging:
  <<: *defaults

production:
  <<: *defaults

```

oh . . .and here's sample parser, but no parser I have works here: 

```
class SJHorses < SupplejackCommon::Json::Base
#a horse specific search against the digitalNZ API
base_url "http://api.digitalnz.org/v3/records.json?api_key=<APIKEY>&fields=title,display_content_partner,creator,landing_url,source_url,thumbnail_url,subject,rights,category,description,id,date,publisher,language,locations&geo_bbox=-41,174,-42,175&text=horse"
  record_selector "$.search.results"
  attribute :display_content_partner, default: "South Pacific Surprise!"
  attribute :category, default: "image"
  attribute :publisher, path: "$.publisher"
  attribute :subject, path: "$.subject"
  attribute :language, path: "$.language"
  attribute :title, path: "$.title"
  attribute :description, path: "$.description", truncate: 170
  attribute :source_url, path: "$.source_url"
  attribute :landing_url, path: "$.landing_url"
  attribute :thumbnail_url, path: "$.thumbnail_url"
  attribute :internal_identifier do get(:landing_url).downcase
	end
  attribute :display_date, path: "$.date", truncate: {length: 4, omission: ""}
  attribute :locations, path: "$.locations"  
end
```

Thanks for considering, 

D.

- supplejack_manager: [ v2.12.9]
- supplejack_worker: [v2.12.14,]
